### ISSUE TITLE
Add support for detection in nested archives

### ISSUE THREAD

**Issue by nmiyake** [palantir/log4j-sniffer#39]
Currently, the detection mechanism only looks into outer archives or nested ZIP archives. However, there are many normal/valid instances where a vulnerability may be in a nested archive (for example, a JAR within a TGZ). The crawling/detection logic should be updated such that all nested archive types are examined recursively.

**Comment by glynternet** [comment]
Closed by https://github.com/palantir/log4j-sniffer/pull/47

**Comment by glynternet** [comment]
Closed by https://github.com/palantir/log4j-sniffer/pull/47
