### ISSUE TITLE
Windows download is in .tgz format not .exe

### ISSUE THREAD

**Issue by TWalstrom** [palantir/log4j-sniffer#50]
Thought I'd comment on this as a common/nontechnical windows user may run into issues:

![image](https://user-images.githubusercontent.com/53358628/147160502-248182f6-a883-4857-8dd7-f66ea0c8ce78.png)

Workaround I utilized:

Ran this command in powershell to convert the linux tgz to exe:
`tar -xvzf C:\Users\USERNAMEHERE\Downloads\log4j-sniffer-1.0.0-windows-amd64.tgz -C C:\Users\USERNAMEHERE\Downloads
`
Then ran this (the .\ at the beginning to allow running in powershell, it's designed for the command prompt):
`.\log4j-sniffer.exe crawl C:\`

**Comment by nkeoleian** [comment]
Hey @TWalstrom, thanks for catching this! Looks like we changed from exe --> tgz between releases 0.8.0 and 1.0.0. I've updated the readme to reflect the correct steps.

**Comment by TWalstrom** [comment]
Awesome, glad I could assist (even if it's something small).
Keep up the amazing work to you and everyone at Palantir!
Cheers 🥂
